using static System.Net.WebRequestMethods;

namespace GroupExpenseManagement01.CommonClasses
{
    public class HtmlTemplate
    {
        public static String AckFeedBack(String UserName)
        {
            return "<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n    <title>Thank You for Your Feedback!</title>\r\n    <style>\r\n        body {\r\n            font-family: Arial, sans-serif;\r\n            background-color: #f4f4f9;\r\n            margin: 0;\r\n            padding: 0;\r\n        }\r\n        .container {\r\n            max-width: 600px;\r\n            margin: 0 auto;\r\n            background-color: #ffffff;\r\n            padding: 20px;\r\n            border-radius: 8px;\r\n            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);\r\n        }\r\n        h1 {\r\n            color: #333333;\r\n        }\r\n        p {\r\n            color: #555555;\r\n        }\r\n        .logo {\r\n            text-align: center;\r\n            margin-bottom: 20px;\r\n        }\r\n        .logo img {\r\n            width: 100%;\r\n            height: auto;\r\n            max-width: 150px;\r\n        }\r\n        .footer {\r\n            margin-top: 20px;\r\n            font-size: 12px;\r\n            color: #888888;\r\n            text-align: center;\r\n        }\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class=\"container\">\r\n        <h1>Thank You, <span id=\"UserName\">" + UserName + "</span>!</h1>\r\n        <p>We appreciate your feedback and are always striving to improve. Your input helps us to better understand your needs and how we can serve you better.</p>\r\n        <p>If you have any further comments, don't hesitate to reach out!</p>\r\n        <p>Best regards,<br>The Team</p>\r\n        <div class=\"logo\">\r\n            <img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmPE7yTUe9LJnDy-IKhQ7O16Ix9jmMD0CBTA&s\" alt=\"Company Logo\" />\r\n        </div>\r\n        <div class=\"footer\">&copy; 2024 Company Name. All rights reserved.</div>\r\n    </div>\r\n</body>\r\n</html>";
        }

        public static String FeedBackToManagers(String UserName, String Email, String Subject, String MSG)
        {
            return "<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n    <title>New User Submission</title>\r\n    <style>\r\n        body {\r\n            font-family: Arial, sans-serif;\r\n            background-color: #f4f4f9;\r\n            margin: 0;\r\n            padding: 0;\r\n        }\r\n        .container {\r\n            max-width: 600px;\r\n            margin: 0 auto;\r\n            background-color: #ffffff;\r\n            padding: 20px;\r\n            border-radius: 8px;\r\n            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);\r\n        }\r\n        h1 {\r\n            color: #333333;\r\n        }\r\n        p {\r\n            color: #555555;\r\n            margin: 0 0 10px;\r\n        }\r\n        .footer {\r\n            margin-top: 20px;\r\n            font-size: 12px;\r\n            color: #888888;\r\n            text-align: center;\r\n        }\r\n        .logo {\r\n            text-align: center;\r\n            margin-bottom: 20px;\r\n        }\r\n        .logo img {\r\n            width: 100%;\r\n            height: auto;\r\n            max-width: 150px;\r\n        }\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class=\"container\">\r\n        <h1>User Feedback</h1>\r\n        <p><strong>Name:</strong> <span id=\"UserName\">"+ UserName + "</span></p>\r\n        <p><strong>Email:</strong> <span id=\"Email\"> " + Email + "</span></p>\r\n        <p><strong>Subject:</strong> <span id=\"Subject\">" + Subject + "</span></p>\r\n        <p><strong>Message:</strong></p>\r\n        <p><span id=\"MSG\">" + MSG + "</span></p>\r\n        <div class=\"logo\" style=\"text-align: center; margin-bottom: 20px;\">\r\n            <img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmPE7yTUe9LJnDy-IKhQ7O16Ix9jmMD0CBTA&s\" alt=\"Company Logo\" />\r\n        </div>\r\n        <div class=\"footer\">&copy; 2024 Company Name. All rights reserved.</div>\r\n    </div>\r\n</body>\r\n</html>";
        }

        public static String Otp(String UserName, int otp)
        {
            return "<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n    <title>Email Verification OTP</title>\r\n    <style>\r\n        body {\r\n            font-family: Arial, sans-serif;\r\n            background-color: #f4f4f9;\r\n            margin: 0;\r\n            padding: 0;\r\n        }\r\n        .container {\r\n            max-width: 600px;\r\n            margin: 0 auto;\r\n            background-color: #ffffff;\r\n            padding: 20px;\r\n            border-radius: 8px;\r\n            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);\r\n        }\r\n        .logo {\r\n            text-align: center;\r\n            margin-bottom: 20px;\r\n        }\r\n        .logo img {\r\n            width: 100%;\r\n            height: auto;\r\n            max-width: 150px; /* Adjust this to fit your needs */\r\n        }\r\n        h1 {\r\n            color: #333333;\r\n            font-size: 20px;\r\n        }\r\n        p {\r\n            color: #555555;\r\n            margin: 0 0 10px;\r\n        }\r\n        .otp-code {\r\n            font-size: 24px;\r\n            font-weight: bold;\r\n            color: #333333;\r\n            margin: 20px 0;\r\n        }\r\n        .footer {\r\n            margin-top: 20px;\r\n            font-size: 12px;\r\n            color: #888888;\r\n            text-align: center;\r\n        }\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class=\"container\">\r\n        \r\n\r\n        <h1>Email Verification OTP</h1>\r\n        <p>Hi " + UserName + ",</p>\r\n        <p>Thank you for registering with us. To complete your registration, please use the following OTP code to verify your email address:</p>\r\n        <p class=\"otp-code\">" + otp + "</p>\r\n        <p>This OTP code is valid for 5 minutes. If you did not request this verification, please disregard this email.</p>\r\n        <p>Best regards,<br>The Team</p>\r\n <div class=\"logo\">\r\n            <img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmPE7yTUe9LJnDy-IKhQ7O16Ix9jmMD0CBTA&s\" alt=\"Company Logo\" />\r\n        </div>\r\n     <div class=\"footer\">\r\n            &copy; 2024 Company Name. All rights reserved.\r\n      </div>\r\n      </div>\r\n\r\n</body>\r\n</html>\r\n";
        }

        public static String ResetPassOtp(String UserName, int otp)
        {
            return "<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n    <title>Forgot Password - OTP Verification</title>\r\n    <style>\r\n        body {\r\n            font-family: Arial, sans-serif;\r\n            background-color: #f4f4f9;\r\n            margin: 0;\r\n            padding: 0;\r\n        }\r\n        .container {\r\n            max-width: 600px;\r\n            margin: 0 auto;\r\n            background-color: #ffffff;\r\n            padding: 20px;\r\n            border-radius: 8px;\r\n            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);\r\n        }\r\n        .logo {\r\n            text-align: center;\r\n            margin-bottom: 20px;\r\n        }\r\n        .logo img {\r\n            width: 100%;\r\n            height: auto;\r\n            max-width: 150px; /* Adjust this to fit your needs */\r\n        }\r\n        h1 {\r\n            color: #333333;\r\n            font-size: 20px;\r\n        }\r\n        p {\r\n            color: #555555;\r\n            margin: 0 0 10px;\r\n        }\r\n        .otp-code {\r\n            font-size: 24px;\r\n            font-weight: bold;\r\n            color: #333333;\r\n            margin: 20px 0;\r\n        }\r\n        .footer {\r\n            margin-top: 20px;\r\n            font-size: 12px;\r\n            color: #888888;\r\n            text-align: center;\r\n        }\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class=\"container\">\r\n        <h1>Forgot Password - OTP Verification</h1>\r\n        <p>Hi " + UserName + ",</p>\r\n        <p>We received a request to reset your password. To verify your identity and proceed with resetting your password, please use the following OTP code:</p>\r\n        <p class=\"otp-code\">" + otp + "</p>\r\n        <p>This OTP code is valid for 5 minutes. If you did not request a password reset, please disregard this email.</p>\r\n        <p>Best regards,<br>The Team</p>\r\n        <div class=\"logo\">\r\n            <img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmPE7yTUe9LJnDy-IKhQ7O16Ix9jmMD0CBTA&s\" alt=\"Company Logo\" />\r\n        </div>\r\n        <div class=\"footer\">\r\n            &copy; 2024 Company Name. All rights reserved.\r\n        </div>\r\n    </div>\r\n</body>\r\n</html>\r\n";
        }

        public static String NewPassword(String UserName, int newPassword)
        {
            // return "<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n    <title>Password Reset - New Password</title>\r\n    <style>\r\n        body {\r\n            font-family: Arial, sans-serif;\r\n            background-color: #f4f4f9;\r\n            margin: 0;\r\n            padding: 0;\r\n        }\r\n        .container {\r\n            max-width: 600px;\r\n            margin: 0 auto;\r\n            background-color: #ffffff;\r\n            padding: 20px;\r\n            border-radius: 8px;\r\n            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);\r\n        }\r\n        .logo {\r\n            text-align: center;\r\n            margin-bottom: 20px;\r\n        }\r\n        .logo img {\r\n            width: 100%;\r\n            height: auto;\r\n            max-width: 150px; /* Adjust this to fit your needs */\r\n        }\r\n        h1 {\r\n            color: #333333;\r\n            font-size: 20px;\r\n        }\r\n        p {\r\n            color: #555555;\r\n            margin: 0 0 10px;\r\n        }\r\n        .new-password {\r\n            font-size: 16px;\r\n            font-weight: bold;\r\n            color: #333333;\r\n            margin: 20px 0;\r\n        }\r\n        .footer {\r\n            margin-top: 20px;\r\n            font-size: 12px;\r\n            color: #888888;\r\n            text-align: center;\r\n        }\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class=\"container\">\r\n        <h1>Password Reset - New Password</h1>\r\n        <p>Hi " + UserName + ",</p>\r\n        <p>Your password has been successfully reset. Below is your new password to access your account:</p>\r\n        <p class=\"new-password\">" + newPassword + "</p>\r\n        <p>For security reasons, we recommend you change your password after logging in.</p>\r\n        <p>If you did not request this password reset, please contact our support team immediately.</p>\r\n        <p>Best regards,<br>The Team</p>\r\n        <div class=\"logo\">\r\n            <img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmPE7yTUe9LJnDy-IKhQ7O16Ix9jmMD0CBTA&s\" alt=\"Company Logo\" />\r\n        </div>\r\n        <div class=\"footer\">\r\n            &copy; 2024 Company Name. All rights reserved.\r\n        </div>\r\n    </div>\r\n</body>\r\n</html>\r\n";
            return "<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n    <title>Password Reset - New Password</title>\r\n    <style>\r\n        body {\r\n            font-family: Arial, sans-serif;\r\n            background-color: #f4f4f9;\r\n            margin: 0;\r\n            padding: 0;\r\n        }\r\n        .container {\r\n            max-width: 600px;\r\n            margin: 0 auto;\r\n            background-color: #ffffff;\r\n            padding: 20px;\r\n            border-radius: 8px;\r\n            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);\r\n        }\r\n        .logo {\r\n            text-align: center;\r\n            margin-bottom: 20px;\r\n        }\r\n        .logo img {\r\n            width: 100%;\r\n            height: auto;\r\n            max-width: 150px;\r\n        }\r\n        h1 {\r\n            color: #333333;\r\n            font-size: 20px;\r\n        }\r\n        p {\r\n            color: #555555;\r\n            margin: 0 0 10px;\r\n        }\r\n        .otp-code {\r\n            font-size: 24px;\r\n            font-weight: bold;\r\n            color: #333333;\r\n            margin: 20px 0;\r\n        }\r\n        .footer {\r\n            margin-top: 20px;\r\n            font-size: 12px;\r\n            color: #888888;\r\n            text-align: center;\r\n        }\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class=\"container\">\r\n        <h1>Password Reset - New Password</h1>\r\n        <p>Hi <span id=\"UserName\">" + UserName + "</span>,</p>\r\n        <p>Your password has been successfully reset. Below is your new password to access your account:</p>\r\n        <p class=\"otp-code\"><span id=\"otp\">" + newPassword + "</span></p>\r\n        <p>For security reasons, we recommend you change your password after logging in.</p>\r\n        <p>If you did not request this password reset, please contact our support team immediately.</p>\r\n        <p>Best regards,<br>The Team</p>\r\n        <div class=\"logo\">\r\n            <img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmPE7yTUe9LJnDy-IKhQ7O16Ix9jmMD0CBTA&s\" alt=\"Company Logo\" />\r\n        </div>\r\n        <div class=\"footer\">\r\n            &copy; 2024 Company Name. All rights reserved.\r\n        </div>\r\n    </div>\r\n</body>\r\n</html>";
        }

        public static String RegistrationConfirmation(String UserName)
        {
            return "<!DOCTYPE html><html lang=\"en\"><head>    <meta charset=\"UTF-8\">    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">    <title>Registration Successful</title>    <style>        body {            font-family: Arial, sans-serif;            background-color: #f4f4f9;            margin: 0;            padding: 0;        }        .container {            max-width: 600px;            margin: 0 auto;            background-color: #ffffff;            padding: 20px;            border-radius: 8px;            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);        }        .logo {            text-align: center;            margin-bottom: 20px;        }        .logo img {            width: 100%;            height: auto;            max-width: 150px; /* Adjust this to fit your needs */        }        h1 {            color: #333333;            font-size: 22px;        }        p {            color: #555555;            margin: 0 0 10px;        }        .footer {            margin-top: 20px;            font-size: 12px;            color: #888888;            text-align: center;        }    </style></head><body>    <div class=\"container\">        <h1>Registration Successful!</h1>        <p>Dear " + UserName + ",</p>        <p>We are excited to inform you that your registration was successful. You can now log in to your account and start using our services.</p>        <p>If you have any questions or need assistance, feel free to reach out to our support team.</p>        <p>Welcome aboard!</p>        <p>Best regards,<br>The Team</p>        <div class=\"logo\">            <img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmPE7yTUe9LJnDy-IKhQ7O16Ix9jmMD0CBTA&s\" alt=\"Company Logo\" />        </div>         <div class=\"footer\">            &copy; 2024 Company Name. All rights reserved.        </div>    </div></body></html>";
        }

        public static String ExportExcel(String UserName)
        {
            return "<!DOCTYPE html><html lang='en'><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1.0'><title>Your Excel File is Ready</title><style>body {font-family: Arial, sans-serif; background-color: #f4f4f9; margin: 0; padding: 0;} .container {max-width: 600px; margin: 0 auto; background-color: #ffffff; padding: 20px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);} h1 {color: #333333;} p {color: #555555;} .logo {text-align: center; margin-bottom: 20px;} .logo img {width: 100%; height: auto; max-width: 150px;} .footer {margin-top: 20px; font-size: 12px; color: #888888; text-align: center;}</style></head><body><div class='container'><h1>Hello, " + UserName + "!</h1><p>We have generated the report you requested, and the Excel file is attached to this email.</p><p>Please review the file at your convenience. If you have any questions or require further assistance, feel free to contact us.</p><p>Best regards,<br>The Team</p><div class='logo'><img src='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmPE7yTUe9LJnDy-IKhQ7O16Ix9jmMD0CBTA&s' alt='Company Logo' /></div><div class='footer'>&copy; 2024 Company Name. All rights reserved.</div></div></body></html>";
        }
    }
    //public class HtmlTemplate
    //{
    //    public static String AckFeedBack(String UserName)
    //    {
    //        return "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Thank You for Your Feedback!</title><style>body {font-family: Arial, sans-serif;background-color: #f4f4f9;margin: 0;padding: 0;}.container {max-width: 600px;margin: 0 auto;background-color: #ffffff;padding: 20px;border-radius: 8px;box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);}h1 {color: #333333;}p {color: #555555;}.logo {text-align: center;margin-bottom: 20px;}.footer {margin-top: 20px;font-size: 12px;color: #888888;text-align: center;}</style></head><body><div class=\"container\"><h1>Thank You, " + UserName + "!</h1><p>We appreciate your feedback and are always striving to improve. Your input helps us to better understand your needs and how we can serve you better.</p><p>If you have any further comments, don't hesitate to reach out!</p><p>Best regards,<br>The Team</p><div class=\"logo\"><img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmPE7yTUe9LJnDy-IKhQ7O16Ix9jmMD0CBTA&s\" alt=\"Company Logo\" style=\"width: 100%; height: auto; max-width: 600px;\" /></div><div class=\"footer\">&copy; 2024 Company Name. All rights reserved.</div></div></body></html>";
    //    }

    //    public static String FeedBackToManagers(String UserName, String Email,String Subject,String MSG) {
    //        return "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>New User Submission</title><style>body {font-family: Arial, sans-serif;background-color: #f4f4f9;margin: 0;padding: 0;}.container {max-width: 600px;margin: 0 auto;background-color: #ffffff;padding: 20px;border-radius: 8px;box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);}h1 {color: #333333;}p {color: #555555;margin: 0 0 10px;}.footer {margin-top: 20px;font-size: 12px;color: #888888;text-align: center;}</style></head><body><div class=\"container\"><h1>User FeedBack</h1><p><strong>Name:</strong>" + UserName + "</p><p><strong>Email:</strong>" + Email + "</p><p><strong>Subject:</strong>" + Subject + "</p><p><strong>Message:</strong></p><p>" + MSG + "</p><div class=\"logo\" style=\"text-align: center; margin-bottom: 20px;\"><img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmPE7yTUe9LJnDy-IKhQ7O16Ix9jmMD0CBTA&s\" alt=\"Company Logo\" style=\"width: 100%; height: auto; max-width: 600px;\" /></div><div class=\"footer\">&copy; 2024 Company Name. All rights reserved.</div></div></body></html>";
    //    }

    //    public static String Otp(String UserName, int otp)
    //    {
    //        return "<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n    <title>Email Verification OTP</title>\r\n    <style>\r\n        body {\r\n            font-family: Arial, sans-serif;\r\n            background-color: #f4f4f9;\r\n            margin: 0;\r\n            padding: 0;\r\n        }\r\n        .container {\r\n            max-width: 600px;\r\n            margin: 0 auto;\r\n            background-color: #ffffff;\r\n            padding: 20px;\r\n            border-radius: 8px;\r\n            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);\r\n        }\r\n        .logo {\r\n            text-align: center;\r\n            margin-bottom: 20px;\r\n        }\r\n        .logo img {\r\n            width: 100%;\r\n            height: auto;\r\n            max-width: 150px; /* Adjust this to fit your needs */\r\n        }\r\n        h1 {\r\n            color: #333333;\r\n            font-size: 20px;\r\n        }\r\n        p {\r\n            color: #555555;\r\n            margin: 0 0 10px;\r\n        }\r\n        .otp-code {\r\n            font-size: 24px;\r\n            font-weight: bold;\r\n            color: #333333;\r\n            margin: 20px 0;\r\n        }\r\n        .footer {\r\n            margin-top: 20px;\r\n            font-size: 12px;\r\n            color: #888888;\r\n            text-align: center;\r\n        }\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class=\"container\">\r\n        \r\n\r\n        <h1>Email Verification OTP</h1>\r\n        <p>Hi " + UserName + ",</p>\r\n        <p>Thank you for registering with us. To complete your registration, please use the following OTP code to verify your email address:</p>\r\n        <p class=\"otp-code\">" + otp + "</p>\r\n        <p>This OTP code is valid for 5 minutes. If you did not request this verification, please disregard this email.</p>\r\n        <p>Best regards,<br>The Team</p>\r\n <div class=\"logo\">\r\n            <img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmPE7yTUe9LJnDy-IKhQ7O16Ix9jmMD0CBTA&s\" alt=\"Company Logo\" />\r\n        </div>\r\n     <div class=\"footer\">\r\n            &copy; 2024 Company Name. All rights reserved.\r\n      </div>\r\n      </div>\r\n\r\n</body>\r\n</html>\r\n";
    //    }

    //    public static String ResetPassOtp(String UserName, int otp)
    //    {
    //        return "<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n    <title>Forgot Password - OTP Verification</title>\r\n    <style>\r\n        body {\r\n            font-family: Arial, sans-serif;\r\n            background-color: #f4f4f9;\r\n            margin: 0;\r\n            padding: 0;\r\n        }\r\n        .container {\r\n            max-width: 600px;\r\n            margin: 0 auto;\r\n            background-color: #ffffff;\r\n            padding: 20px;\r\n            border-radius: 8px;\r\n            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);\r\n        }\r\n        .logo {\r\n            text-align: center;\r\n            margin-bottom: 20px;\r\n        }\r\n        .logo img {\r\n            width: 100%;\r\n            height: auto;\r\n            max-width: 150px; /* Adjust this to fit your needs */\r\n        }\r\n        h1 {\r\n            color: #333333;\r\n            font-size: 20px;\r\n        }\r\n        p {\r\n            color: #555555;\r\n            margin: 0 0 10px;\r\n        }\r\n        .otp-code {\r\n            font-size: 24px;\r\n            font-weight: bold;\r\n            color: #333333;\r\n            margin: 20px 0;\r\n        }\r\n        .footer {\r\n            margin-top: 20px;\r\n            font-size: 12px;\r\n            color: #888888;\r\n            text-align: center;\r\n        }\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class=\"container\">\r\n        <h1>Forgot Password - OTP Verification</h1>\r\n        <p>Hi " + UserName + ",</p>\r\n        <p>We received a request to reset your password. To verify your identity and proceed with resetting your password, please use the following OTP code:</p>\r\n        <p class=\"otp-code\">" + otp + "</p>\r\n        <p>This OTP code is valid for 5 minutes. If you did not request a password reset, please disregard this email.</p>\r\n        <p>Best regards,<br>The Team</p>\r\n        <div class=\"logo\">\r\n            <img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmPE7yTUe9LJnDy-IKhQ7O16Ix9jmMD0CBTA&s\" alt=\"Company Logo\" />\r\n        </div>\r\n        <div class=\"footer\">\r\n            &copy; 2024 Company Name. All rights reserved.\r\n        </div>\r\n    </div>\r\n</body>\r\n</html>\r\n";
    //    }

    //    public static String NewPassword(String UserName, int newPassword)
    //    {
    //        return "<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n    <title>Password Reset - New Password</title>\r\n    <style>\r\n        body {\r\n            font-family: Arial, sans-serif;\r\n            background-color: #f4f4f9;\r\n            margin: 0;\r\n            padding: 0;\r\n        }\r\n        .container {\r\n            max-width: 600px;\r\n            margin: 0 auto;\r\n            background-color: #ffffff;\r\n            padding: 20px;\r\n            border-radius: 8px;\r\n            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);\r\n        }\r\n        .logo {\r\n            text-align: center;\r\n            margin-bottom: 20px;\r\n        }\r\n        .logo img {\r\n            width: 100%;\r\n            height: auto;\r\n            max-width: 150px; /* Adjust this to fit your needs */\r\n        }\r\n        h1 {\r\n            color: #333333;\r\n            font-size: 20px;\r\n        }\r\n        p {\r\n            color: #555555;\r\n            margin: 0 0 10px;\r\n        }\r\n        .new-password {\r\n            font-size: 16px;\r\n            font-weight: bold;\r\n            color: #333333;\r\n            margin: 20px 0;\r\n        }\r\n        .footer {\r\n            margin-top: 20px;\r\n            font-size: 12px;\r\n            color: #888888;\r\n            text-align: center;\r\n        }\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class=\"container\">\r\n        <h1>Password Reset - New Password</h1>\r\n        <p>Hi " + UserName + ",</p>\r\n        <p>Your password has been successfully reset. Below is your new password to access your account:</p>\r\n        <p class=\"new-password\">" + newPassword + "</p>\r\n        <p>For security reasons, we recommend you change your password after logging in.</p>\r\n        <p>If you did not request this password reset, please contact our support team immediately.</p>\r\n        <p>Best regards,<br>The Team</p>\r\n        <div class=\"logo\">\r\n            <img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmPE7yTUe9LJnDy-IKhQ7O16Ix9jmMD0CBTA&s\" alt=\"Company Logo\" />\r\n        </div>\r\n        <div class=\"footer\">\r\n            &copy; 2024 Company Name. All rights reserved.\r\n        </div>\r\n    </div>\r\n</body>\r\n</html>\r\n";
    //    }

    //    public static String RegistrationConfirmation(String UserName)
    //    {
    //        return "<!DOCTYPE html><html lang=\"en\"><head>    <meta charset=\"UTF-8\">    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">    <title>Registration Successful</title>    <style>        body {            font-family: Arial, sans-serif;            background-color: #f4f4f9;            margin: 0;            padding: 0;        }        .container {            max-width: 600px;            margin: 0 auto;            background-color: #ffffff;            padding: 20px;            border-radius: 8px;            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);        }        .logo {            text-align: center;            margin-bottom: 20px;        }        .logo img {            width: 100%;            height: auto;            max-width: 150px; /* Adjust this to fit your needs */        }        h1 {            color: #333333;            font-size: 22px;        }        p {            color: #555555;            margin: 0 0 10px;        }        .footer {            margin-top: 20px;            font-size: 12px;            color: #888888;            text-align: center;        }    </style></head><body>    <div class=\"container\">        <h1>Registration Successful!</h1>        <p>Dear " + UserName + ",</p>        <p>We are excited to inform you that your registration was successful. You can now log in to your account and start using our services.</p>        <p>If you have any questions or need assistance, feel free to reach out to our support team.</p>        <p>Welcome aboard!</p>        <p>Best regards,<br>The Team</p>        <div class=\"logo\">            <img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmPE7yTUe9LJnDy-IKhQ7O16Ix9jmMD0CBTA&s\" alt=\"Company Logo\" />        </div>         <div class=\"footer\">            &copy; 2024 Company Name. All rights reserved.        </div>    </div></body></html>";
    //    }

    //    public static String ExportExcel(String UserName)
    //    {
    //        return "<!DOCTYPE html><html lang='en'><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1.0'><title>Your Excel File is Ready</title><style>body {font-family: Arial, sans-serif; background-color: #f4f4f9; margin: 0; padding: 0;} .container {max-width: 600px; margin: 0 auto; background-color: #ffffff; padding: 20px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);} h1 {color: #333333;} p {color: #555555;} .logo {text-align: center; margin-bottom: 20px;} .logo img {width: 100%; height: auto; max-width: 150px;} .footer {margin-top: 20px; font-size: 12px; color: #888888; text-align: center;}</style></head><body><div class='container'><h1>Hello, " + UserName + "!</h1><p>We have generated the report you requested, and the Excel file is attached to this email.</p><p>Please review the file at your convenience. If you have any questions or require further assistance, feel free to contact us.</p><p>Best regards,<br>The Team</p><div class='logo'><img src='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmPE7yTUe9LJnDy-IKhQ7O16Ix9jmMD0CBTA&s' alt='Company Logo' /></div><div class='footer'>&copy; 2024 Company Name. All rights reserved.</div></div></body></html>";
    //    }
    //}
}
